
development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB'] %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  username: <%= ENV['DB_ENV_POSTGRES_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_TEST'] %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  username: <%= ENV['DB_ENV_POSTGRES_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB'] %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  username: <%= ENV['DB_ENV_POSTGRES_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>
  pool: 5
